server:  
 port: 9091  

#Application Properties
spring:
 application:
  name: USER-SERVICE

# Zipkin for Tracing and Identify Latency Issue
  zipkin:
   base-url: http://localhost:9411/zipkin/

#Database Connections
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/java-fsd
  username: root
  password: root

 jpa:
  hibernate.ddl-auto: update
  generate-ddl: True

#Fault Tolerance Application
resilience4j.retry:
 instace:
  userService:
   maxRetryAttempts: 3
   maxDuration: 50000
  

